language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

notifications:
  email: false

install:
    - pip install -U tox-travis coverage codecov

script:
  - tox

after_success: coverage combine && codecov
