---
extends: default

rules:
  line-length:
    max: 100
    level: error

  comments:
    require-starting-space: false
    min-spaces-from-content: 1

  comments-indentation:
    ignore: |
      .pre-commit-config.yaml
