version: '3.5'


services:

  # DoH server container
  doh_server:
    networks:
      traefik_proxy:
        ipv4_address: 172.16.0.3

  # pihole container
  pihole:
    networks:
      traefik_proxy:
        ipv4_address: 172.16.0.4

  # træfik container
  traefik:
    container_name: traefik
    hostname: ${HOSTNAME}
    image: traefik:latest
    environment:
      - TZ=${TZ:-Europe/London}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-docker/configs/:/etc/traefik/
      - ./traefik-docker/shared/:/shared/:ro
      - ./certificates/certs:/etc/ssl/certs/
      - ./certificates/private/:/etc/ssl/private/
    ports:
      - "80:80"
      - "443:443"
      - "853:853"
      - "8080:8080"
    networks:
      traefik_proxy:
        ipv4_address: 172.16.0.250
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
  ##### http
    ### routers
      # traefik dashboard
      - traefik.http.routers.rou_Traefik.entrypoints=https
      - traefik.http.routers.rou_Traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.rou_Traefik.tls=true
      - traefik.http.routers.rou_Traefik.tls.options=default
      - traefik.http.routers.rou_Traefik.middlewares=mdw_SecureHeaders@file
      - traefik.http.routers.rou_Traefik.service=api@internal


networks:
  # Bridge network for træfik's communication
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: 172.16.0.0/24
    attachable: false