version: '3.5'


services:

  # DoH server container
  doh_server:
    networks:
      traefik_proxy:
        ipv4_address: 172.16.0.3

  # pihole container
  pihole:
    networks:
      traefik_proxy:
        ipv4_address: 172.16.0.4

  # nginx container
  nginx:
    container_name: nginx
    hostname: ${HOSTNAME}
    image: nginx:1.17
    volumes:
      - ./nginx-docker/configs/:/etc/nginx/
      - ./certificates/certs/:/etc/ssl/certs/
      - ./certificates/private/:/etc/ssl/private/
      - ./certificates/dhparam.pem:/etc/nginx/dhparam.pem
    expose:
      - 853
    networks:
      dns_network0:
        ipv4_address: 172.16.1.2
      traefik_proxy:
        ipv4_address: 172.16.0.2
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
  ##### tcp
    ### services
      # backend port
      - traefik.tcp.services.svc_NginxDot.loadbalancer.server.port=853
    ### routers
      # DoT forward
      - traefik.tcp.routers.rou_NginxDot.entrypoints=dot
      - traefik.tcp.routers.rou_NginxDot.rule=HostSNI(`dot.${DOMAIN}`)
      - traefik.tcp.routers.rou_NginxDot.tls.passthrough=true
      - traefik.tcp.routers.rou_NginxDot.service=svc_NginxDot

  # træfik container
  traefik:
    container_name: traefik
    hostname: ${HOSTNAME}
    image: traefik:v2.0
    environment:
      - TZ=${TZ:-Europe/London}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-docker/configs/:/etc/traefik/
      - ./traefik-docker/shared/:/shared/:ro
      - ./certificates/certs:/etc/ssl/certs/
      - ./certificates/private/:/etc/ssl/private/
    ports:
      - "80:80"
      - "443:443"
      - "853:853"
      - "8080:8080"
    networks:
      traefik_proxy:
        ipv4_address: 172.16.0.250
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
  ##### http
    ### routers
      # traefik dashboard
      - traefik.http.routers.rou_Traefik.entrypoints=https
      - traefik.http.routers.rou_Traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.rou_Traefik.tls=true
      - traefik.http.routers.rou_Traefik.tls.options=default
      - traefik.http.routers.rou_Traefik.middlewares=mdw_SecureHeaders@file
      - traefik.http.routers.rou_Traefik.service=api@internal


networks:
  # Bridge network for træfik's communication
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: 172.16.0.0/24
    attachable: false