version: '3.5'


services:

  # nginx container
  nginx:
    container_name: nginx
    hostname: ${HOST_NAME}
    image: nginx:1.17
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./nginx-docker/configs/:/etc/nginx/
      - ./nginx-docker/templates/:/etc/nginx/templates/
      - ./certificates/cert.crt:/etc/ssl/certs/cert.crt
      - ./certificates/key.key:/etc/ssl/private/key.key
      - ./certificates/dhparam.pem:/etc/nginx/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
      - "853:853"
    networks:
      dns_network0:
        ipv4_address: 172.16.1.2
    restart: always
    command: >-
      /bin/bash -c
      "envsubst < /etc/nginx/templates/443.conf.template > /etc/nginx/sites-enabled/443.conf &&
      nginx -g 'daemon off;'"