version: '3.5'


services:

  # træfik container
  traefik:
    container_name: traefik
    hostname: ${HOST_NAME}
    image: traefik:v2.0
    environment:
      - TZ=${TIMEZONE:-Europe/London}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-docker/configs/:/etc/traefik/
      - ./traefik-docker/shared/:/shared/:ro
      - ./certificates/cert.crt:/etc/ssl/certs/cert.crt
      - ./certificates/key.key:/etc/ssl/private/key.key
    ports:
      - "80:80"
      - "443:443"
      - "853:853"
      - "8080:8080"
    networks:
      dns_network:
        ipv4_address: 172.16.1.250
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=dns_network
  ##### https
    ### middleware
      # dashboard auth
      - traefik.http.middlewares.mdw_TraefikAuth.basicauth.usersfile=/shared/.htpasswd
      # dashboard chain
      - traefik.http.middlewares.mdw_TraefikChainNoAuth.chain.middlewares=mdw_SecureHeaders@file
      - traefik.http.middlewares.mdw_TraefikChainAuth.chain.middlewares=mdw_SecureHeaders@file,mdw_TraefikAuth
    ### routers
      # traefik dashboard
      - traefik.http.routers.rou_Traefik.entrypoints=https
      - traefik.http.routers.rou_Traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.rou_Traefik.tls=true
      - traefik.http.routers.rou_Traefik.tls.options=default
      - traefik.http.routers.rou_Traefik.middlewares=mdw_TraefikChain${TRAEFIK_AUTH:-NoAuth}
      - traefik.http.routers.rou_Traefik.service=api@internal