########################################################################################################################
#
# Configuration file for Traefik v2.0.
#
########################################################################################################################



########################################################################################################################
# Header configuration
########################################################################################################################

[http.middlewares]

  [http.middlewares.mdw_SecureHeaders.headers]
    sslRedirect=true
    forceSTSHeader=true
    STSIncludeSubdomains=true
    STSSeconds=63072000
    STSPreload=true
    browserXSSFilter=true
    contentTypeNosniff=true
    frameDeny=true
