########################################################################################################################
#
# Configuration file for Traefik v2.0.
#
########################################################################################################################



########################################################################################################################
# TLS configuration
########################################################################################################################

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS13"
    curvePreferences = ["X25519", "CurveP521", "CurveP384"]
    sniStrict = true
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    ]

[[tls.certificates]]
  certFile = "/etc/ssl/certs/cert.crt"
  keyFile = "/etc/ssl/private/key.key"
