########################################################################################################################
#
# Configuration file for Traefik v2.0.
#
########################################################################################################################



########################################################################################################################
# Traefik global configuration
########################################################################################################################

[global]
  checkNewVersion = true
  sendAnonymousUsage = false


########################################################################################################################
# API and dashboard configuration
########################################################################################################################

[api]
  dashboard = true

[ping]
  entryPoint = "http"


########################################################################################################################
# Traefik logs configuration
########################################################################################################################

[log]
  level = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC

[accessLog]


########################################################################################################################
# Entrypoints configuration
########################################################################################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"

  [entryPoints.dot]
  address = ":853"


########################################################################################################################
# Traefik provider configuration
########################################################################################################################

[providers]
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

  [providers.file]
    watch = true
    directory = "/etc/traefik/traefik.conf.d/"