########################################################################################################################
#
# Configuration file for Traefik v2.0.
#
########################################################################################################################



########################################################################################################################
# Traefik global configuration
########################################################################################################################

[global]
  checkNewVersion = true
  sendAnonymousUsage = false


########################################################################################################################
# API and dashboard configuration
########################################################################################################################

[api]
  dashboard = true
  insecure = false
  debug = false

[ping]
  entryPoint = "http"


########################################################################################################################
# Log configuration
########################################################################################################################

[log]
  level = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common" #json
#  filePath = "/path/to/traefik.log"

[accessLog]
  format = "common" #json
#  filePath = "/path/to/traefik_access.log"


########################################################################################################################
# Entrypoint configuration
########################################################################################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"

  [entryPoints.dot]
  address = ":853"


########################################################################################################################
# Provider configuration
########################################################################################################################

[providers]
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

  [providers.file]
    watch = true
    directory = "/etc/traefik/traefik.conf.d/"
